version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: people-survey-api
    depends_on:
      - postgres
    env_file:
      - ./.envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "8008:8008"

  postgres:
    image: postgres:13
    container_name: people-survey-postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/web
    ports:
      - "5432:5432"

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z
