# Generated by Django 3.2.15 on 2022-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220823_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
